services:
  mariadb:
    image: bitnami/mariadb:latest
    container_name: moodle_db
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASS}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'

  moodle:
    image: bitnami/moodle:4.5
    container_name: moodle
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      - MOODLE_DATABASE_HOST=${DB_HOST}
      - MOODLE_DATABASE_PORT_NUMBER=${DB_PORT}
      - MOODLE_DATABASE_USER=${DB_USER}
      - MOODLE_DATABASE_PASSWORD=${DB_PASS}
      - MOODLE_DATABASE_NAME=${DB_NAME}
      - MOODLE_SMTP_HOST=${SMTP_HOST}
      - MOODLE_SMTP_PORT=${SMTP_PORT}
      - MOODLE_SMTP_AUTH=${SMTP_AUTH}
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
      - mailpit

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local